allowBuilds: {}

shamefullyHoist: true

configDependencies:
  pnpm-plugin-nice-move: 0.3.6+sha512-r29ZIK+qcmhe98Jv8hchUBCGnM37P73iDLlHGEZGzM00e9SGYYMaJ6qLeeUer1zakblBzIAbsn2F2IiF8UoZWQ==

trustPolicyExclude:
  - semver@6.3.1
